# Generated by Django 4.1.2 on 2022-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('nombrecont', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
    ]
