# Generated by Django 4.1.2 on 2022-10-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_tblsucursales'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.tblsucursales')),
            ],
        ),
    ]
