# Generated by Django 4.1.2 on 2022-10-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_compras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblEmpleados',
        ),
        migrations.DeleteModel(
            name='tblProveedores',
        ),
        migrations.DeleteModel(
            name='tblSucursales',
        ),
    ]
